### ISSUE TITLE
Unable to yarn build on M1 Mac

### ISSUE THREAD

**Issue by songproducer** [lousando/briskett#9]
yarn build
```
● Client █████████████████████████ compiling (0%)  
 

◯ Server
  


 ERROR  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/leotreasure/briskett/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/leotreasure/briskett/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/leotreasure/briskett/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/leotreasure/briskett/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/leotreasure/briskett/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/leotreasure/briskett/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/leotreasure/briskett/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/leotreasure/briskett/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/leotreasure/briskett/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/leotreasure/briskett/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/leotreasure/briskett/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/leotreasure/briskett/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/leotreasure/briskett/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/leotreasure/briskett/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/leotreasure/briskett/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/leotreasure/briskett/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/leotreasure/briskett/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/leotreasure/briskett/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/leotreasure/briskett/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/leotreasure/briskett/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/leotreasure/briskett/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/leotreasure/briskett/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/leotreasure/briskett/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/leotreasure/briskett/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/leotreasure/briskett/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(base) leotreasure@Leos-MBP briskett % node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 64052.
    at /Users/leotreasure/briskett/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: undefined,
  signal: undefined
}

Node.js v17.2.0
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 64053.
    at /Users/leotreasure/briskett/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: undefined,
  signal: undefined
}

Node.js v17.2.0
```

**Comment by lousando** [comment]
I mostly develop on Ubuntu, but I have a Mac I can test this on. Just off the top.. is this reproducible on an Intel based Macbook?

**Comment by lousando** [comment]
@songproducer I was able to build on an Intel based Mac. Please provide more details of your setup.

**Comment by songproducer** [comment]
Sorry, yes I'm using Apple M1 Max Monterey 12.1
